### ISSUE TITLE
Don't commit MaxMind license key to your repository

### ISSUE THREAD

**Issue by ugexe** [fengzhao/fengzhao-notes#31]
https://github.com/fengzhao/fengzhao-notes/blob/3d5a576bd9ba1012bc973519f671b27ec0da984f/nginx/1.nginx%E9%98%BB%E6%AD%A2%E7%89%B9%E5%AE%9A%E5%9C%B0%E5%8C%BA%E8%AE%BF%E9%97%AE.markdown?plain=1#L67

**Comment by fengzhao** [comment]
OK，thank you
